spring:
  profiles:
    include: int
  datasource:
    url: jdbc:mysql://${DATABASE_ADDRESS:localhost}/${DATABASE_NAME:faf}?useSSL=false
    name: ${DATABASE_NAME:faf}
    username: ${DATABASE_USERNAME:faf-java-api}
    password: ${DATABASE_PASSWORD:banana}
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: ${DATABASE_DDL_AUTO:none}
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        current_session_context_class: org.springframework.orm.hibernate5.SpringSessionContext
  h2:
    console:
      enabled: true


faf-api:
  jwt:
    secretKey: |-
      -----BEGIN RSA PRIVATE KEY-----
      MIIEpgIBAAKCAQEAzTpJ/ytBu3dih41bEqRnchNfkyCigIWDHrbBa+0Szw853Oew
      LJ1Zwe5wh9L8nxWD7f+pVDg5dAKXAJabmx6vuXhJjekIxrHTIRdxebO2norhAK/Q
      OuOZ4NKinShpWwyLgmPcJZaKq1TNtVm7No/3CQK5XugDJ5NG2c1RNEAdk3pk2EkB
      lhhObJW2vUY+KmJ+4ndwZKeyJD4CTr4sJK7cWRf2Ht2RWq6omFlsnQiPGyO9/VYo
      YQz3fVTiXdf4+xg6toBaVvult0YPS5/jm611RrsMwLM4ZpWkUlytxR/N8/oLb9rD
      nO9+OQZDpIsKfNd3ZAqg/wZTHIcb474UHjUTiQIDAQABAoIBAQCMuO1IZNbbvs72
      97x9GfI8zH/6mKQU0HfKNbKHWLZO+LfKe6vXy8ViLydGWywRwWUHawkm0K7El4oH
      Qz5LrUz9NjfpcOMtq32D8VlEBDCyobQLDoMP/kTjXktWzAECB6YZsHOh6ooHVU0A
      jxjKHwlbSlzlcN3I4znv2tNVqqkdF9Gbg7wUmN9n0qpj+7kDtkixJy3jm9YLxKCS
      pNZ1UUjGKtVgl/1871slNUtANHj/xCnkYrOncrIXf472pEeSxBU5JlI4fILcyTtG
      B9btuYBk7Z239TWDEZTqIyst0QGteNRsjE+gkB9WV1ra9JPPWDiBYye4qqaIs3al
      jd3lkMApAoGBAP+i1aJ/c8XV18eTMYLmQZRnkjrkxyQMhJ/x+6tow6p6A16lDwHh
      tRoyQk0XdTpQegu+YtdBXSRk6zNzE2njWEVOMK4/Zqt5a1yMSE/8MMQVler1ChdF
      PWhZCPb+CfKm1RHXpFMsmBZx+7MumLQwjCtZfQl8YMt34gfVcXRSZ50DAoGBAM2F
      FVrTTUVaGv6zjdO7K+5eUj0VRR2nGId5nIWqouQryJaizeBZfWatjDYVbl0qHFy2
      QnHA+3UEsVWOkJG90rZcP4UWcDy86e5T/3FR2Xfy3kW10Gfe6hrjjbjYflleD5Qg
      uZ9ovk/TZjTjvMWisNBSW1FILz9SMLWHoCFPGOmDAoGBANKRb4X1lAiOt7n13d+k
      CLrUgVgvoHVqNkiFi7dKiXnAHUx1i6ISKBoW8hQMUYyiQ5Wu0j3a4n0a/74WeRRM
      pyYXXPP613hBgJTwHJR9+DFcUmwCQbifWRC93iuNX+ZXU8Tpqrq0TeaXJywWIsSy
      BJOkl+EbaaPP8Qhg4Z5eTmi/AoGBAMzSDyA/acjuLe0cwQH8jaG3+rnJkuIkf3u0
      pVtJXaGMSRJnGkq2pRVJbG0SGrVanH2BXuLDc1eB38HmnQnCZlc7xEo8vIqrs2/D
      4tXqvpKeRwquUg7Sx/kYQ0uu5uzloxz7KENIPjKL+lZHiQBmTVSwXzW4fO3cWZLw
      oZPQooFFAoGBAMVvhsOmlpwyyS9s/CVIMirvLQEuEIIS5fMcnmCmu8P49ZZ7YSVf
      2OJOSGj+lWkEMf2qOW7kYl303GrESeJ36KmLbDthnH+p6RSq5NzN5CAucffA0tsa
      keX0a6YHVu9doUPhUFJdbgg8FIL1FVEJROQckMAiDcYg2mFXmtaVTjqX
      -----END RSA PRIVATE KEY-----
    publicKey: |-
      ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDNOkn/K0G7d2KHjVsSpGdyE1+TIKKAhYMetsFr7RLPDznc57AsnVnB7nCH0vyfFYPt/6lUODl0ApcAlpubHq+5eEmN6QjGsdMhF3F5s7aeiuEAr9A645ng0qKdKGlbDIuCY9wlloqrVM21Wbs2j/cJArle6AMnk0bZzVE0QB2TemTYSQGWGE5slba9Rj4qYn7id3Bkp7IkPgJOviwkrtxZF/Ye3ZFarqiYWWydCI8bI739VihhDPd9VOJd1/j7GDq2gFpW+6W3Rg9Ln+ObrXVGuwzAszhmlaRSXK3FH83z+gtv2sOc7345BkOkiwp813dkCqD/BlMchxvjvhQeNROJ api@faforever.com
  map:
    target-directory: "build/cache/map/maps"
    directory-preview-path-small: "build/cache/map_previews/small"
    directory-preview-path-large: "build/cache/map_previews/large"
    small-previews-url-format: "http://localhost/faf/vault/map_previews/small/%s"
    large-previews-url-format: "http://localhost/faf/vault/map_previews/large/%s"
    download-url-format: "http://localhost/faf/vault/maps/%s"
  avatar:
    download-url-format: "http://localhost/faf/avatars/%s"
    target-directory: "build/cache/avatars"
    allowed-extensions: "png"
    max-size-bytes: 4096
    image-width: 40
    image-height: 20
  clan:
    website-url-format: "http://example.com/%s"
  tutorial:
    thumbnail-url-format: "http://test.com/faf/tutorials/%s/xyz"
  user:
    minimum-days-between-username-change: 30
  mail:
    from-email-name: "integration-test@faforever.com"
    from-email-address: "integration-test@faforever.com"
  password-reset:
    password-reset-url-format: "http://localhost:8010/users/claimPasswordResetToken/%s"
    success-redirect-url: "http://localhost/password_resetted"
    subject: "Integration test password reset"
    html-format: "Integration test password reset html body"
  registration:
    activation-url-format: "http://localhost/users/activate?token=%s"
    success-redirect-url: "http://localhost/account_activated"
    subject: "Integration test registration"
    html-format: "Integration test registration html body"
  link-to-steam:
    steam-redirect-url-format: "http://localhost:8010/users/linkToSteam?token=%s"
  steam:
    realm: "http://localhost"
    api-key: "banana"
  replay:
    download-url-format: "http://localhost/faf/vault/replay_vault/replay.php?id=%s"
  mautic:
    client-id: banana
    client-secret: banana


logging:
  level:
    org.springframework.security: DEBUG
